language: scala

scala:
  - 2.10.4
  - 2.11.4
  
jdk:
- oraclejdk8

before_script:
- echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, TRAVIS_BRANCH=$TRAVIS_BRANCH"

script: scripts/ci-build

notifications:
  email: false
